name: golangci-lint
on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [opened, synchronize]
    branches:
      - '*'
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # pin@8.0.0
        with:
          args: -v --timeout=5m
          skip-build-cache: true
          skip-pkg-cache: true
